### ISSUE TITLE
need file path prefix

### ISSUE THREAD

**Issue by mehmetkose** [hillmanov/gulp-manifest#28]
dude, I'm sending static files to amazon s3 with gulp, every change. so I need prefix_path option.

**Comment by mehmetkose** [comment]
I used this guy's fork. https://github.com/veiset/gulp-manifest
i think you should merge this changes.
https://github.com/hillmanov/gulp-manifest/pull/23/files

**Comment by hillmanov** [comment]
Supported now. Thanks!

**Comment by mehmetkose** [comment]
cool. thank you.
