### ISSUE TITLE
Broken paths

### ISSUE THREAD

**Issue by satya164** [hillmanov/gulp-manifest#34]
The generated manifest file no longer generates correct paths. for example, I've files under, `/public/s/`, when I run `gulp-manifest` with the options

```
      {
		basePath: "public",
		network: [ "*" ],
		timestamp: true,
		filename: "manifest.appcache"
	}
```

It produces,

```
CACHE MANIFEST
# Time: Mon Sep 07 2015 11:24:43 GMT+0000 (UTC)


CACHE:
scrollback-logo-dark.png
scrollback-logo-dark@2x.png
scrollback-logo-white.png
scrollback-logo-white@2x.png
scrollback-logo.png
scrollback-logo@2x.png
fonts/icons.eot
fonts/icons.svg
fonts/icons.ttf
fonts/icons.woff
scripts/app.bundle.min.js
styles/embed.min.css
styles/style.min.css


NETWORK:
*
```

It should produce this,

```
CACHE MANIFEST
# Time: Mon Sep 07 2015 11:29:40 GMT+0000 (UTC)


CACHE:
/s/assets/logo/scrollback-logo-dark.png
/s/assets/logo/scrollback-logo-dark@2x.png
/s/assets/logo/scrollback-logo-white.png
/s/assets/logo/scrollback-logo-white@2x.png
/s/assets/logo/scrollback-logo.png
/s/assets/logo/scrollback-logo@2x.png
/s/dist/fonts/icons.eot
/s/dist/fonts/icons.svg
/s/dist/fonts/icons.ttf
/s/dist/fonts/icons.woff
/s/dist/scripts/app.bundle.min.js
/s/dist/styles/embed.min.css
/s/dist/styles/style.min.css


NETWORK:
*
```

The absence of the paths is a biggie for me, which means cache will no longer work :(

This basically reverts https://github.com/hillmanov/gulp-manifest/pull/17 which is a genuine case.

I think the commit https://github.com/hillmanov/gulp-manifest/commit/4962ce06bb1fa66b6ef4fc9df443c8bf7fd77b3f is the culprit.

Can we please revert that commit, since it's a breaking change and doesn't provide any additional features, while breaking the existing ones.

**Comment by gronke** [comment]
@satya164 sorry for breaking your config. I'm working on this issue right now and as first step writing more unit tests to drill down what's going wrong.

Could you please share your Gulp task beginning from `gulp.src`?

**Comment by gronke** [comment]
@satya164 there's PR #35 to fix this issue

I don't think having a `basePath` option is necessary, because paths [should be resolved properly](https://github.com/gulpjs/gulp/blob/master/docs/API.md#optionsbase) before  being piped into this plugin, e.g.

```javascript
var mergeStream = require('merge-stream');
var manifestPlugin = require('gulp-manifest');
return mergeStream(
  gulp.src('dist/**', {
    base: 'dist/'
  }),
  gulp.src('assets/**', {
    base: 'assets/'
  })
).
pipe(manifestPlugin())
...
```

The mentioned PR brings back this behavior, but leaves a deprecation notice in your gulp stdout to stay downwards compatible until the next major version bump.

**Comment by satya164** [comment]
@gronke Sorry for late reply. Been very busy over the week.

Hmm... I didn't know the about `base` option in `gulp.src`. It fixes my issue. Thanks.

However I find it very weird the way file paths are generated, when I don't specify a base.

For example, the following is my gulp task,

```
gulp.task("manifest", () =>
	gulp.src([
		"public/s/assets/logo/*",
		"public/s/dist/**/*",
		"!**/{*.map,config.json,LICENSE.txt}"
	])
	.pipe(plumber())
	.pipe(manifest({
		network: [ "*" ],
		timestamp: true,
		filename: "manifest.appcache"
	}))
	.pipe(gulp.dest("public"))
);
```

It generates this manifest file,

```
CACHE MANIFEST
# Time: Sat Sep 12 2015 14:11:21 GMT+0530 (IST)


CACHE:
scrollback-logo-dark.png
scrollback-logo-dark@2x.png
scrollback-logo-white.png
scrollback-logo-white@2x.png
scrollback-logo.png
scrollback-logo@2x.png
fonts/icons.eot
fonts/icons.svg
fonts/icons.ttf
fonts/icons.woff
scripts/app.bundle.min.js
styles/embed.min.css
styles/style.min.css


NETWORK:
*
```

But when I have a base option,

```
gulp.task("manifest", () =>
	gulp.src([
		"public/s/assets/logo/*",
		"public/s/dist/**/*",
		"!**/{*.map,config.json,LICENSE.txt}"
	], { base: "public/" })
	.pipe(plumber())
	.pipe(manifest({
		network: [ "*" ],
		timestamp: true,
		filename: "manifest.appcache"
	}))
	.pipe(gulp.dest("public"))
);
```

It will generate this,

```
CACHE MANIFEST
# Time: Sat Sep 12 2015 14:13:37 GMT+0530 (IST)


CACHE:
s/assets/logo/scrollback-logo-dark.png
s/assets/logo/scrollback-logo-dark@2x.png
s/assets/logo/scrollback-logo-white.png
s/assets/logo/scrollback-logo-white@2x.png
s/assets/logo/scrollback-logo.png
s/assets/logo/scrollback-logo@2x.png
s/dist/fonts/icons.eot
s/dist/fonts/icons.svg
s/dist/fonts/icons.ttf
s/dist/fonts/icons.woff
s/dist/scripts/app.bundle.min.js
s/dist/styles/embed.min.css
s/dist/styles/style.min.css


NETWORK:
*
```

Here the first one becomes totally usable, as it just lists the file names from the directories `public/s/assets/logo/` and `public/s/dist/`.

**Comment by kwv** [comment]
possible dupe.   4962ce0  also reintroduces https://github.com/hillmanov/gulp-manifest/issues/4

**Comment by gronke** [comment]
@satya164 the output without gulp.src.base specified looks correct, because gulp.src is looking for files relative to each fileglob, unless a common base path is specified. Leaving notes on this behavior in the Readme and some unit tests that point out this behavior explicitly will help getting around this issue.

**Comment by satya164** [comment]
@gronke that's what my pull request is for, adding notes in the readme.
