### ISSUE TITLE
Version 0.1.0 is not in a NPM repository

### ISSUE THREAD

**Issue by mrzepinski** [hillmanov/gulp-manifest#38]
As a title says - @hillmanov :)

**Comment by stingstrom** [comment]
+1
Eager to get this for the windows backslash workaround.

**Comment by hillmanov** [comment]
@gronke Are we ready to publish to npm?

**Comment by gronke** [comment]
Always ready :smirk: all tests pass

**Comment by hillmanov** [comment]
@mrzepinski Done!
