### ISSUE TITLE
Windows path name support

### ISSUE THREAD

**Issue by timdp** [hillmanov/gulp-manifest#4]
It looks like Windows path names confuse this plugin. I have the following task set up:

```coffeescript
gulp.task "manifest", ->
  gulp.src([ "public/**/*", "!public/app.manifest" ])
    .pipe(manifest(
      hash: true
      preferOnline: true
      network: [
        "http://*"
        "https://*"
        "*"
      ]
    ))
    .pipe(gulp.dest("public/app.manifest"))
```

This does not create the manifest file.

If I dump the value of `manifestContents`, I *almost* get the expected result. However, the `CACHE:` section contains escaped full path names such as:

```
c:%5Chtdocs%5Ctmdpw.eu%5Cpublic%5Cfavicon.ico
```

This is on Windows 8.1 x64 with node.js v0.11.11 (unstable) and Gulp 3.5.2.

Additionally, I ran the same code on Heroku, which didn't create the file either. Has Gulp's API changed? If you like, I'll open a separate issue for that, but maybe there's something wrong with my task instead?

**Comment by kwv** [comment]
4962ce0  introduces a regression on this item.   Build-platform specific path delimiters are causing issues.  

i.e. built on a windows:

```
CACHE MANIFEST

CACHE:
index.html
scripts%5Capp.js
styles%5Capp.css

NETWORK:
*
```

**Comment by gronke** [comment]
@kwv thanks, will look into this shortly! *waiting for windows vm install*

**Comment by gronke** [comment]
More tests added.

@kwv does https://github.com/gronke/gulp-manifest/blob/test-gulp-src-base/test/main.js#L173-L189 cover your issue scenario?
